### ISSUE TITLE
Support found identity notification in various ways

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/rekor-monitor#140]
- [ ] File GH issue
- [ ] Send email (Sendgrid support first)
- [ ] Tweet?

**Comment by haydentherapper** [comment]
For sending email, we'll need a mapping between identity and email if the identity is not an email address.

**Comment by asraa** [comment]
>  identity and email if the identity is not an email address.

I wonder if this could also be an input.

Imagine that I want to sneakily monitor for things YOU sign (or in a better world, some signing service account that's jointly owned by me and other maintainers) but I want to receive the notification on my email address.

**Comment by richardfan1126** [comment]
Why not just set the found identity info as the workflow output, and let the caller actions do whatever they want on it?

**Comment by haydentherapper** [comment]
Thanks for taking a look at this @richardfan1126! I didn't flesh out this issue very much, but we'd like to avoid coupling this too tightly to GitHub Actions, as we'd like the monitor to be easy to run in other environments with the same set of features.

@linus-sun is taking a look at proposing an updated structured output where tools can ingest that output and handle notifications themselves, along with an API that takes in that structured output and handles notifications from the binary, with an interface to support implementers adding new notifications.

**Comment by haydentherapper** [comment]
@linus-sun has added emails and GitHub issues, so we'll consider this closed.
