### ISSUE TITLE
[feature] Support OID extension monitoring

### ISSUE THREAD

**Issue by asraa** [sigstore/rekor-monitor#158]
**Description**

SLSA GitHub generators use Sigstore signing to sign releases. Trusted builders use their GH provided OIDC identity to sign. The source repository is contained inside OID extensions, and later with enhancements, the caller workflow job ref will be as well. If rekor-monitor supports OID extension monitoring, users can monitor their package builds.

**Comment by haydentherapper** [comment]
Here are the Sigstore OIDs we should support monitoring for: https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md

**Comment by linus-sun** [comment]
picking this up!

**Comment by haydentherapper** [comment]
This is now completed!
