### ISSUE TITLE
Refactoring test files

### ISSUE THREAD

**Issue by efebarlas** [sigstore/rekor-monitor#21]
Most of the tests of the mirroring, polling and log-handler packages are end-to-end, which means that the tests involve API calls. Currently, api.sigstore.dev is used to check results with expected values, which are defined statically. Therefore, the tests fail as the log updates.

We have two options:
There could be a mock API interface, but this is not possible as the API calls are done via rekor's pkg code, which cannot be modified to use mock interfaces.

The second option is to run e2e tests like rekor does, that is, to run a local log using a bash script and instantiate it inside the test bench, then send API calls to localhost.

**Comment by efebarlas** [comment]
Update: gomock allows to mock interfaces, hence, the three ClientService interfaces of *client.Rekor can be mocked easily. As such, e2e tests are not needed (at least for now).

**Comment by haydentherapper** [comment]
Tests have been cleaned up
