### ISSUE TITLE
What should happen if consistency check fails?

### ISSUE THREAD

**Issue by hojoung97** [sigstore/rekor-monitor#33]
**Question**

Things in Question:
- Return values from `VerifySignedTreeHead` when there is inconsistency
- Action to take in mirroring `main.go` when there is inconsistency

**Comment by hojoung97** [comment]
```
verifier := logverifier.New(rfc6962.DefaultHasher)
err = verifier.VerifyConsistencyProof(oldSize, *logInfo.TreeSize, oldRoot, newRoot, proofs)
if err != nil {
    return 0, "", err
}
```
Currently, `VerifySignedTreeHead` returns `0, "", err` upon any error (including inconsistency)

**Comment by haydentherapper** [comment]
No longer an issue
