### ISSUE TITLE
ComputeRoot potential memory problems

### ISSUE THREAD

**Issue by efebarlas** [sigstore/rekor-monitor#5]
Right now, the ComputeRoot function in mirroring/pkg/rekorClient.go uses a container/list object (doubly linked list) to compute the signed root hash bottom-up. 

This method requires an entire row of the tree to be stored in memory at the same time, which might be troublesome when the tree in question is too large. This function could benefit from rewriting.

**Comment by haydentherapper** [comment]
Removing the mirroring functionality, so closing issue as outdated
