### ISSUE TITLE
Decouple log checkpoint file from identity monitor via reading in from separate identity metadata file

### ISSUE THREAD

**Issue by linus-sun** [sigstore/rekor-monitor#519]
**Description**

[Noted here](https://github.com/sigstore/rekor-monitor/blob/48375db9da425b4d9985ca13cb9f854b4f59439d/cmd/monitor/main.go#L126): rather than fetching indices to monitor from via reading from a log checkpoint file, the identity monitor can write to a separate identity metadata file listing the last monitored log index, which it can use as its start index for subsequent runs. This further separates usage of the consistency check and identity monitor.

**Comment by haydentherapper** [comment]
Marking as closed. We decided to continue to use the checkpoint index.
