### ISSUE TITLE
Enhancement: Caching intermediate hashes

### ISSUE THREAD

**Issue by efebarlas** [sigstore/rekor-monitor#9]
This would make computing the root hash from cached leaves a lot easier when we are running a consistency proof between the cached and fetched trees for polling.

I'm not sure how this can be easily and efficiently done with a file. The "hash file" should have the following properties:

- appends should do the trick: otherwise we would need to shift entries which is hefty for large logs
- should contain enough information for the computeRoot function to run in a time period without regards to the actual size of the tree, if possible O(n) where n is the number of new leaves appended.

Right now, polling confirms the STH by computing the tree hash from scratch using cached leaves. This might create problems when the log is larger.

**Comment by haydentherapper** [comment]
Removing the mirroring functionality, so closing issue as outdated
